2025-03-09 19:30:04,824 INFO    MainThread:31368 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/shuvrajeet/Documents/GitHub/DA6401_DeepLearning_Assignment1/wandb/run-20250309_193004-Question-1/logs/debug.log
2025-03-09 19:30:04,824 INFO    MainThread:31368 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/shuvrajeet/Documents/GitHub/DA6401_DeepLearning_Assignment1/wandb/run-20250309_193004-Question-1/logs/debug-internal.log
2025-03-09 19:30:04,824 INFO    MainThread:31368 [wandb_init.py:init():761] calling init triggers
2025-03-09 19:30:04,824 INFO    MainThread:31368 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-09 19:30:04,824 INFO    MainThread:31368 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 19:30:04,835 WARNING MsgRouterThr:31368 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/shuvrajeet/miniconda3/envs/da6401_dl/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/da6401_dl/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/da6401_dl/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shuvrajeet/miniconda3/envs/da6401_dl/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/da6401_dl/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-09 19:30:04,836 INFO    MsgRouterThr:31368 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
